databases:
  - name: culture-db
    databaseName: culture
    user: culture
    plan: free

services:
  - type: web
    name: culture-app
    env: php
    plan: free
    region: frankfurt # Optional, but good for latency in Africa/Europe
    buildCommand: chmod +x bin/deploy.sh && ./bin/deploy.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true # Keep true for initial debug, switch to false later
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://culture-app.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: culture-db
          property: connectionString
      - key: FEDAPAY_PUBLIC_KEY
        sync: false
      - key: FEDAPAY_SECRET_KEY
        sync: false
      - key: FEDAPAY_ENV
        value: sandbox
